"""remove original_link, add imdb_id

Revision ID: 38f457e3cf5f
Revises: 64ede7bfaeb7
Create Date: 2026-01-30 15:52:18.545958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f457e3cf5f'
down_revision: Union[str, Sequence[str], None] = '64ede7bfaeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('imdb_id', sa.Integer(), nullable=True))
    op.drop_column('movies', 'original_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('original_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('movies', 'imdb_id')
    # ### end Alembic commands ###
